wandb_version: 1

seed:
  desc: null
  value: 300
lr:
  desc: null
  value: 0.09
dataset:
  desc: null
  value: cifar-10
epochNumber:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699911254.459101
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
