wandb_version: 1

batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.01
optimizer:
  desc: null
  value: adagrad
val_batch_size:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699724210.389522
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.12
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
