program: downsampled_cifar_training.py
method: random  # or grid
metric:
  goal: maximize  # or minimize
  name: accuracy  # the metric you want to optimize
parameters:
  scheduler_gamma:
    min: 0.1
    max: 1.0
  scheduler_step_size:
    values: [1, 2, 3]
  batch_size:
    values: [16, 32, 64]
  dropout_prob:
    values: [0.1, 0.2, 0.3]
  optimizer_choice:
    values: [ 'sgd', 'adam', 'rmsprop', 'adagrad' ]
  learning_rate:
    values: [0.5 ,0.3, 0.1, 0.01]