wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: MLP
dataset:
  desc: null
  value: CIFAR-10
epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699896229.382988
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
