wandb_version: 1

batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.06325741844091773
num_epochs:
  desc: null
  value: 150
dataset:
  desc: null
  value: CIFAR-10
epochs:
  desc: null
  value: 150
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699915807.699587
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      - 24
      - 37
      4: 3.9.6
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
